blank_issues_enabled: false
contact_links:
    - name: Ask a Question
      url: https://github.com/spatie/laravel-mailcoach/discussions/new?category=q-a
      about: Ask for help
    - name: Feature Request
      url: https://github.com/spatie/laravel-mailcoach/discussions/new?category=ideas
      about: Share ideas for new features
